In [1]:
#导入NumPy
from numpy import * 
#定义数组a
a = array( [2,3,4] )
#调用dtype输出素组元素类型
print('a=',a)
print('数组元素类型：', a.dtype) 

a= [2 3 4]
数组元素类型： int32


In [2]:
b = array([1.2, 3.5, 5.1])
print('b=',b)
print('数组元素类型：', b.dtype)

b= [1.2 3.5 5.1]
数组元素类型： float64


In [3]:
#定义二维数组c
c = array([(1.5,2,3),(4,5,6)]) 
print('c=',c)
print('数组元素类型：', c.dtype)

c= [[1.5 2.  3. ]
 [4.  5.  6. ]]
数组元素类型： float64


In [4]:
#定义复数元素数组d
#元素类型限定为complex64
d = array([[1,2], [3,4]], dtype=complex64)   
print('d=',d)
print('数组元素类型：',d.dtype)

d= [[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]
数组元素类型： complex64


In [5]:
#定义3*4的二维数组e，并使用0填充
e = zeros((3,4))                 
print('e=',e)
print('数组元素类型：',e.dtype)

e= [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
数组元素类型： float64


In [6]:
#定义2*3*4的三维数组f，并使用1填充
#元素类型限定为int16
f = ones((2,3,4),dtype=int16)    
print('f=',f)
print('数组元素类型：',f.dtype)

f= [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
数组元素类型： int16


In [7]:
#定义数组g，取值范围为[10,30),元素增长步长为5，
#注意区间开闭
g = arange(10,30,5)           
print('g=',g)
print('数组元素类型：', g.dtype)

g= [10 15 20 25]
数组元素类型： int32


In [8]:
#定义数组h，取值范围为[0,2),元素增长步长为0.3，
#注意区间开闭
h = arange(0,2,0.3)          
print('h=',h)
print('数组元素类型：',h.dtype)

h= [0.  0.3 0.6 0.9 1.2 1.5 1.8]
数组元素类型： float64


In [9]:
#定义数组i，取值范围为[0,14),缺省步长为1，并调用reshape将其设置为3*5的数组
#显示数组i的各项属性
i = arange(15).reshape(3, 5)
print('i=',i)
print('数组轴个数：', i.ndim)
print('数组形状：', i.shape)
print('数组元素总个数：', i.size)
print('数组元素类型：', i.dtype)
print('数组元素字节大小：', i.itemsize)
print('数组数据缓冲区地址：', i.data)

i= [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
数组轴个数： 2
数组形状： (3, 5)
数组元素总个数： 15
数组元素类型： int32
数组元素字节大小： 4
数组数据缓冲区地址： <memory at 0x000001DFA8C498B8>


In [10]:
#定义一维数组j，取值范围为[0,10000),观察其输出
j = arange(10000)
print('j=',j)
print()
#定义100*100的二维数组k，,观察其输出
k = arange(10000).reshape(100,100)
print('k=',k)

j= [   0    1    2 ... 9997 9998 9999]

k= [[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


In [11]:
#重新对以上cell中的数组名进行赋值
a = array([20,30,40,50])
b = arange(4)
print('原始数组：')
print('a=',a)
print('b=',b)

原始数组：
a= [20 30 40 50]
b= [0 1 2 3]


In [12]:
#数组减法运算
c = a-b
print('c= (a-b) =', c)

c= (a-b) = [20 29 38 47]


In [13]:
#数组元素乘方
b_2=b**2
print('b_2= b*b =',b_2)

b_2= b*b = [0 1 4 9]


In [14]:
#数组元素求正弦值，再*10
a_s=10*sin(a)
print('a_s=10*sin(a)=',a_s)

a_s=10*sin(a)= [ 9.12945251 -9.88031624  7.4511316  -2.62374854]


In [15]:
#数组元素条件运算
a_cond=(a<35)
print('a_cond=(a<35)=',a_cond)

a_cond=(a<35)= [ True  True False False]


In [16]:
#数组元素乘法*与矩阵乘法dot，进一步地说明请看本章第3节
d = array([[1,1],[0,1]])
e = array([[2,0],[3,4]])
print('二维数组d：')
print(d)
print('二维数组e：')
print(e)
print('元素乘法，其运算方法是两个2维数组对应的元素直接相乘')
print('元素乘法：d*e')
print(d*e)
print('矩阵dot乘法，其运算方法是按照线性代数定义的两个矩阵相乘进行运算')
print('矩阵乘法：dot(d,e)')
print(dot(d,e))

二维数组d：
[[1 1]
 [0 1]]
二维数组e：
[[2 0]
 [3 4]]
元素乘法，其运算方法是两个2维数组对应的元素直接相乘
元素乘法：d*e
[[2 0]
 [0 4]]
矩阵dot乘法，其运算方法是按照线性代数定义的两个矩阵相乘进行运算
矩阵乘法：dot(d,e)
[[5 4]
 [3 4]]


In [17]:
#操作符像+=和*=被用来更改已存在数组而不创建一个新的数组
#random用于产生随机数，每次运行结果不相同
f = ones((2,3), dtype=int)
g = random.random((2,3))
print('f=',f)
print('g=',g)
f*=3
g+=f
print('f=',f)
print('g=',g)

f= [[1 1 1]
 [1 1 1]]
g= [[0.76919368 0.9318623  0.95302062]
 [0.063401   0.32400379 0.30239984]]
f= [[3 3 3]
 [3 3 3]]
g= [[3.76919368 3.9318623  3.95302062]
 [3.063401   3.32400379 3.30239984]]


In [18]:
#求数组元素的和、最小值、最大值
print('g.sum()=',g.sum())
print('g.min()=',g.min())
print('g.max()=',g.max())

g.sum()= 21.343881226735075
g.min()= 3.063400996814575
g.max()= 3.953020615607664


In [19]:
#按照指定的轴axis，求最大值
print('axis=0，表示按照列进行运算')
print('g.max(axis=0)=',g.max(axis=0))
print('axis=1，表示按照行进行运算')
print('g.max(axis=1)=',g.max(axis=1))

axis=0，表示按照列进行运算
g.max(axis=0)= [3.76919368 3.9318623  3.95302062]
axis=1，表示按照行进行运算
g.max(axis=1)= [3.95302062 3.32400379]


In [20]:
#对数组排序
h = random.random(10)
print('随机数组：',h)
print('排序后：',sort(h))

随机数组： [0.21658998 0.08419669 0.01705242 0.83531918 0.41017418 0.9751095
 0.32318922 0.7083756  0.43348643 0.62166618]
排序后： [0.01705242 0.08419669 0.21658998 0.32318922 0.41017418 0.43348643
 0.62166618 0.7083756  0.83531918 0.9751095 ]


In [21]:
#布尔索引，输出满足特定条件的元素
x = array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])  
print ('数组是：')
print (x)
# 现在打印出大于 5 的元素  
print('大于 5 的元素是：')
print(x[x > 5])

数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
大于 5 的元素是：
[ 6  7  8  9 10 11]


In [22]:
#用下标/索引访问数组元素
a=[1,2,3,4,5,6,7,8,9,10]
print('a[2]=',a[2])
#用冒号：来对数组切片,请注意起止区间
print('a[2:5]=',a[2:5])

a[2]= 3
a[2:5]= [3, 4, 5]


In [23]:
#行/列访问
x = array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print('二维数组x：')
print(x)
print('访问第2行:',x[2,:])
print('访问第2列:',x[:,2])

二维数组x：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
访问第2行: [6 7 8]
访问第2列: [ 2  5  8 11]


In [24]:
#逆序
a=[1,2,3,4,5,6,7,8,9,10]
print('数组逆序操作:')
print('a[::-1]=',a[::-1])

数组逆序操作:
a[::-1]= [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [25]:
#迭代运算,以下代码表示构造一个5行4列的2维素组，
#每个元素的值为10*横坐标x+纵坐标y
def func1(x,y):
    return 10*x+y
b = fromfunction(func1,(5,4),dtype=int)
print('b=',b)

b= [[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


In [26]:
#二维数组切片,注意起止区间！
print('二维数组切片,注意起止区间！')
print('b[2,3]=',b[2,3])
print('b[0:5,1]=',b[0:5,1])
print('b[ : ,1]=',b[ : ,1])
print('b[1:3, : ]=',b[1:3, : ])

二维数组切片,注意起止区间！
b[2,3]= 23
b[0:5,1]= [ 1 11 21 31 41]
b[ : ,1]= [ 1 11 21 31 41]
b[1:3, : ]= [[10 11 12 13]
 [20 21 22 23]]


In [27]:
#逐行操作。注意，此时输出是5个独立数组
print('将b按行分拆成5个独立数组输出：')
for row in b:
    print(row)

将b按行分拆成5个独立数组输出：
[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [28]:
#构造一个用0填充的2行2列矩阵
import numpy as np 
a=np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [29]:
#构造一个用1填充的3行3列矩阵
b=np.ones((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [30]:
#构造3行3列单位矩阵
c=np.identity(3)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
#构造3行3列[1,10]之间的随机整数矩阵
d=np.random.randint(1,11,(3,3))
print(d)

[[10  5  8]
 [10  5  6]
 [ 2  6  2]]


In [32]:
#构造3行3列服从0，1分布的正态随机矩阵
e=np.random.randn(3,3)
print(e)

[[ 0.29431625 -1.92304821  0.03189478]
 [ 0.04544197 -0.91897049 -0.54758752]
 [-0.40284206 -1.00830478  2.07326681]]


In [33]:
a=np.array([[1,2],[3,4]]) 
b=np.array([[5,6],[7,8]])
print('矩阵a：')
print(a)
print('矩阵b：')
print(b)

print('a矩阵与b矩阵相乘的结果是：')
c= matmul(a,b)
print(c)

print('a矩阵与b矩阵dot运算的结果是：')
d=dot(a,b)
print(d)
print()

e=np.array([1,2,3])
f=np.array([4,5,6])
print('向量e：')
print(e)
print('向量f：')
print(f)

print('e向量与f向量内积的结果是：')
g= inner(e,f)
print(g)

print('e向量与f向量dot运算的结果是：')
h=dot(e,f)
print(h)

矩阵a：
[[1 2]
 [3 4]]
矩阵b：
[[5 6]
 [7 8]]
a矩阵与b矩阵相乘的结果是：
[[19 22]
 [43 50]]
a矩阵与b矩阵dot运算的结果是：
[[19 22]
 [43 50]]

向量e：
[1 2 3]
向量f：
[4 5 6]
e向量与f向量内积的结果是：
32
e向量与f向量dot运算的结果是：
32


In [34]:
a=np.array([[1,2],[3,4]])
print('矩阵a：')
print(a)
print()

print('矩阵a对应的行列式的值是：')
b=np.linalg.det(a)
print(b)
print()

print('矩阵a对应的逆矩阵是：')
c=np.linalg.inv(a)
print(c)
print()

print('矩阵a对应的特征值和特征向量是：')
d=np.linalg.eig(a)
print('特征值：',d[0])
print('特征向量：',d[1])

矩阵a：
[[1 2]
 [3 4]]

矩阵a对应的行列式的值是：
-2.0000000000000004

矩阵a对应的逆矩阵是：
[[-2.   1. ]
 [ 1.5 -0.5]]

矩阵a对应的特征值和特征向量是：
特征值： [-0.37228132  5.37228132]
特征向量： [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [35]:
#必须引入scipy包，用于求解线性方程
from scipy.linalg import solve
a = np.array([[3, 1, -2], [1, -1, 4], [2, 0, 3]])
b = np.array([5, -2, 2.5])
print('方程形如Ax=b，其中A=')
print(a)
print('其中b=',b)
print()
print('方程的解为：')
x = solve(a, b)
print(x)

方程形如Ax=b，其中A=
[[ 3  1 -2]
 [ 1 -1  4]
 [ 2  0  3]]
其中b= [ 5.  -2.   2.5]

方程的解为：
[0.5 4.5 0.5]


In [36]:
import numpy as np

#定义一维数组 a,由10个1-100之间随机数构成，请注意起始值和终值。
a = np.random.randint(1,101,10)
#定义一维数组 b,由1，2，……10构成
b = np.arange(1,11)
#定义一维数组 c,由10个符合N（0，1）正态分布的随机数构成
c = np.random.randn(10)
#定义一维数组 d,由10个符合N（1，4）分布的随机数构成
d = np.random.randn(10)*2+1
print('原始数据:', a)  
print('原始数据:', b) 
print('原始数据:', c)
print('原始数据:', d)  
  
#输出最大、最小值及结构
#此处结构是指维度、行列信息
print('最小值:', a.min())  
print('最大值:', a.max())  
print('结构', a.shape)  
  
#数据切片  
print('切片操作:')  
print(a[:-2])  
print(a[-2:])  
print(a[:1])  
  
#排序  
print(type(a))  
a.sort()  
print('排序后:', a)

原始数据: [43 47 62 72 33 22 27 15 25 78]
原始数据: [ 1  2  3  4  5  6  7  8  9 10]
原始数据: [ 0.31846553  1.62965486 -2.54308736 -0.4208588  -0.46515452 -1.00041729
  1.85343977 -0.52793276 -0.06644821  1.53229219]
原始数据: [ 1.29957796  1.81122286 -1.83304288  0.81389536 -2.62016749 -0.38130996
 -0.80587258  1.68481004  0.00499059  2.23730022]
最小值: 15
最大值: 78
结构 (10,)
切片操作:
[43 47 62 72 33 22 27 15]
[25 78]
[43]
<class 'numpy.ndarray'>
排序后: [15 22 25 27 33 43 47 62 72 78]


In [37]:
import numpy as np  

#2行3列二维数组，用0填充
e = np.zeros([2,3])
#3行2列二维数组，用1填充
f = np.ones([3,2])
print('e:',e)
print('f:',f)

#手工输入3行4列二维数组h
h = np.array([[1, 2, 3, 4],[4, 5, 6, 7], [7, 8, 9, 10]])
#获取值  
print('h结构:', h.shape)  
print('获取值:', h[1][0])  
print('获取某行:',h[1][:])  
print('获取某行并切片:',h[0][:-1])
print('获取某行并切片:',h[0][-1:])  
#获取具体某列值  
print('获取第3列:')  
print(h[:,np.newaxis, 2])  

#2行3列二维数组，用1-10之间随机数填充
i = np.random.randint(1,10,(2,3))
print('i:',i)

#调用sin函数  
print(np.sin(np.pi/6))  
print(type(np.sin(0.5))) 
  
#范围定义  
print(np.arange(0,4))  
print(type(np.arange(0,4)))

e: [[0. 0. 0.]
 [0. 0. 0.]]
f: [[1. 1.]
 [1. 1.]
 [1. 1.]]
h结构: (3, 4)
获取值: 4
获取某行: [4 5 6 7]
获取某行并切片: [1 2 3]
获取某行并切片: [4]
获取第3列:
[[3]
 [6]
 [9]]
i: [[2 1 3]
 [9 6 7]]
0.49999999999999994
<class 'numpy.float64'>
[0 1 2 3]
<class 'numpy.ndarray'>
